version: '3.8'
services:
  rest-api:
    build:
      context: ./rest-api/

  nginx-proxy:
    build:
      context: ./nginx/
      args:
        ENABLED_MODULES: ndk lua
    ports:
      - 8080:8080
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      UPSTREAM_URL: "http://rest-api:5000"
